# Site settings
title: Smallyard Blog 
header-img: img/home-bg.jpg
email: liuhongqiang@live.cn
description: "Smallyard 博客。 @小小已然 | @smallyard | @小院子 "
baseurl: ""
url: "http://blog.smallyard.cn"
#twitter_username: smallyard
github_username:  liuhongqiang
#facebook_username:  smallyard
weibo_username: smallyard
zhihu_username: smallyard

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
